collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8924731
  brandStrength: 1
  lightness: 0.5089605
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
  rhythmicContrast: 0.1989247
typography_spectrum: 0.4462366
layout_spectrum: 0.9623656
name: Tandrom rathner
